# Generated by Django 2.1.8 on 2019-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='158A4C855D00437E8A57799E8BEE3B2C', max_length=64, unique=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('permissionName', models.CharField(blank=True, max_length=128, null=True, verbose_name='权限名称')),
                ('permissionCode', models.CharField(blank=True, max_length=128, null=True, verbose_name='权限编码')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='158A4C855D00437E8A57799E8BEE3B2C', max_length=64, unique=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('roleName', models.CharField(blank=True, max_length=128, null=True, verbose_name='角色名称')),
                ('roleCode', models.CharField(blank=True, max_length=128, null=True, verbose_name='角色编码')),
                ('isDelete', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(to='common.Permissions')),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='158A4C855D00437E8A57799E8BEE3B2C', max_length=64, unique=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('userID', models.CharField(default=None, max_length=64)),
                ('nickName', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('realName', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3)),
                ('tel', models.CharField(blank=True, max_length=32, null=True)),
                ('dateBirth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('point', models.IntegerField(default=0, verbose_name='用户积分')),
                ('lastVist', models.DateTimeField(blank=True, null=True, verbose_name='上次访问时间')),
                ('avatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='用户头像')),
                ('isDelete', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(to='common.Role')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
